---
employees:
  - whopper
  - HAIL9000
  - branan
  - Magisus
  - kylog
  - seangriff
  - Iristyle
  - er0ck
  - ferventcoder
  - johnduarte
  - thallgren
  - joshcooper
  - hlindberg
  - peterhuene
  - MikaelSmith
  - puppetcla
  - melissa
  - underscorgan
  - shrug
  - geoffnichols
  - justinstoller
  - cprice404
  - KevinCorcoran
  - rlinehan
  - nathanielksmith
  - gguillotte
  - nfagerlund
  - jtappa
  - McdonaldSeanp
  - ahenroid
  - glennsarti
  - adrienthebo
  - kbarber
  - nicklewis
  - shermdog
  - MosesMendoza
  - adreyer
  - phongdly
